import type { CSSProperties } from 'react';

export const ui: Record<string, CSSProperties> = {
  wrapper: {
    maxWidth: '1300px',
    margin: '0 auto',
    padding: '32px 20px',
  },
  header: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: '24px',
  },
  brand: {
    display: 'flex',
    alignItems: 'center',
    gap: '16px',
  },
  logoBox: {
    width: '48px',
    height: '48px',
    borderRadius: '12px',
    backgroundColor: '#151c28',
    border: '1px solid #232d3f',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    boxShadow: '0 4px 12px rgba(0,0,0,0.2)',
  },
  title: {
    fontSize: '22px',
    fontWeight: 700,
    margin: 0,
    letterSpacing: '-0.5px',
  },
  subtitle: {
    fontSize: '13px',
    color: '#9ca3af',
    margin: '4px 0 0 0',
  },
  refreshBtn: {
    display: 'flex',
    alignItems: 'center',
    gap: '8px',
    backgroundColor: '#151c28',
    color: '#f3f4f6',
    border: '1px solid #232d3f',
    padding: '10px 18px',
    borderRadius: '10px',
    cursor: 'pointer',
    fontFamily: 'Vazirmatn',
    fontWeight: 500,
    fontSize: '14px',
    transition: 'all 0.2s',
  },
  statusStrip: {
    backgroundColor: '#151c28',
    border: '1px solid #232d3f',
    borderRadius: '12px',
    padding: '12px 20px',
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: '28px',
  },
  grid4: {
    display: 'grid',
    gridTemplateColumns: 'repeat(auto-fit, minmax(260px, 1fr))',
    gap: '20px',
    marginBottom: '28px',
  },
  card: {
    backgroundColor: '#151c28',
    border: '1px solid #232d3f',
    borderRadius: '16px',
    padding: '20px',
    boxShadow: '0 4px 20px rgba(0,0,0,0.15)',
  },
  cardTop: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    color: '#9ca3af',
    fontSize: '14px',
    fontWeight: 500,
  },
  iconBadge: {
    width: '36px',
    height: '36px',
    borderRadius: '8px',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
  },
  cardValGroup: {
    display: 'flex',
    alignItems: 'baseline',
    gap: '8px',
    marginTop: '16px',
  },
  cardNum: {
    fontSize: '32px',
    fontWeight: 700,
  },
  subNum: {
    fontSize: '12px',
    color: '#9ca3af',
  },
  progressBg: {
    height: '6px',
    backgroundColor: '#232d3f',
    borderRadius: '10px',
    marginTop: '16px',
    overflow: 'hidden',
  },
  progressBar: {
    height: '100%',
    borderRadius: '10px',
    transition: 'width 0.4s ease',
  },
  chartSection: {
    backgroundColor: '#151c28',
    border: '1px solid #232d3f',
    borderRadius: '16px',
    padding: '24px',
    marginBottom: '28px',
  },
  sectionTitle: {
    fontSize: '17px',
    fontWeight: 700,
    margin: 0,
  },
  sectionSubtitle: {
    fontSize: '13px',
    color: '#9ca3af',
    margin: '4px 0 0 0',
  },
  alertSection: {
    backgroundColor: '#151c28',
    border: '1px solid rgba(239, 68, 68, 0.2)',
    borderRadius: '16px',
    padding: '24px',
  },
  alertGrid: {
    display: 'grid',
    gridTemplateColumns: 'repeat(auto-fit, minmax(280px, 1fr))',
    gap: '12px',
    marginTop: '16px',
  },
  alertItem: {
    backgroundColor: 'rgba(239, 68, 68, 0.05)',
    borderRight: '4px solid #ef4444',
    padding: '14px',
    borderRadius: '8px',
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
  },
  severityTag: {
    backgroundColor: '#ef4444',
    color: '#fff',
    fontSize: '10px',
    fontWeight: 700,
    padding: '2px 6px',
    borderRadius: '4px',
  },
  alertAction: {
    display: 'inline-flex',
    alignItems: 'center',
    gap: '4px',
    backgroundColor: 'transparent',
    color: '#f3f4f6',
    border: '1px solid #232d3f',
    borderRadius: '8px',
    padding: '6px 10px',
    cursor: 'pointer',
    fontFamily: 'Vazirmatn',
    fontSize: '12px',
  },
  monitorForm: {
    display: 'grid',
    gridTemplateColumns: 'repeat(auto-fit, minmax(180px, 1fr))',
    gap: '12px',
    alignItems: 'end',
    marginTop: '18px',
  },
  monitorLabel: {
    display: 'flex',
    flexDirection: 'column',
    gap: '6px',
    fontSize: '12px',
    color: '#9ca3af',
  },
  monitorInput: {
    backgroundColor: '#0b0f17',
    color: '#f3f4f6',
    border: '1px solid #232d3f',
    borderRadius: '10px',
    padding: '10px 12px',
    fontFamily: 'inherit',
    fontSize: '14px',
  },
  monitorSubmit: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    gap: '6px',
    backgroundColor: '#6366f1',
    color: '#fff',
    border: 'none',
    borderRadius: '10px',
    padding: '10px 16px',
    cursor: 'pointer',
    fontFamily: 'Vazirmatn',
    fontWeight: 600,
    fontSize: '13px',
    whiteSpace: 'nowrap',
  },
  monitorList: {
    display: 'flex',
    flexDirection: 'column',
    gap: '10px',
    marginTop: '18px',
  },
  monitorRow: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    gap: '12px',
    backgroundColor: '#0b0f17',
    border: '1px solid #232d3f',
    borderRadius: '12px',
    padding: '14px 16px',
  },
  monitorDelete: {
    backgroundColor: 'transparent',
    color: '#9ca3af',
    border: '1px solid #232d3f',
    borderRadius: '8px',
    padding: '8px',
    cursor: 'pointer',
    display: 'flex',
  },
};
