import type { CSSProperties } from 'react';

export const ui: Record<string, CSSProperties> = {
  wrapper: {
    maxWidth: '1240px',
    margin: '0 auto',
    padding: '28px 20px 48px',
  },
  header: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    gap: '18px',
    flexWrap: 'wrap',
    marginBottom: '22px',
  },
  brand: {
    display: 'flex',
    alignItems: 'center',
    gap: '14px',
  },
  logoBox: {
    width: '52px',
    height: '52px',
    borderRadius: '16px',
    background:
      'linear-gradient(145deg, rgba(15,122,114,0.16), rgba(29,111,138,0.1))',
    border: '1px solid var(--border-color)',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
  },
  title: {
    fontSize: '26px',
    fontWeight: 800,
    margin: 0,
    letterSpacing: '-0.03em',
    color: 'var(--text-main)',
  },
  subtitle: {
    fontSize: '13px',
    color: 'var(--text-muted)',
    margin: '6px 0 0 0',
  },
  refreshBtn: {
    display: 'flex',
    alignItems: 'center',
    gap: '8px',
    backgroundColor: 'var(--bg-solid)',
    color: 'var(--text-main)',
    border: '1px solid var(--border-color)',
    padding: '10px 14px',
    borderRadius: '999px',
    cursor: 'pointer',
    fontFamily: 'var(--font-ui)',
    fontWeight: 600,
    fontSize: '13px',
    boxShadow: '0 8px 18px rgba(21, 45, 40, 0.04)',
  },
  statusStrip: {
    backgroundColor: 'var(--bg-elevated)',
    backdropFilter: 'blur(10px)',
    border: '1px solid var(--border-color)',
    borderRadius: 'var(--radius-lg)',
    padding: '14px 18px',
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    gap: '12px',
    flexWrap: 'wrap',
    marginBottom: '22px',
    boxShadow: 'var(--shadow-soft)',
  },
  grid4: {
    display: 'grid',
    gridTemplateColumns: 'repeat(auto-fit, minmax(230px, 1fr))',
    gap: '16px',
    marginBottom: '22px',
  },
  card: {
    backgroundColor: 'var(--bg-elevated)',
    backdropFilter: 'blur(10px)',
    border: '1px solid var(--border-color)',
    borderRadius: 'var(--radius-lg)',
    padding: '18px',
    boxShadow: 'var(--shadow-soft)',
  },
  cardTop: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    color: 'var(--text-muted)',
    fontSize: '13px',
    fontWeight: 600,
  },
  iconBadge: {
    width: '36px',
    height: '36px',
    borderRadius: '10px',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
  },
  cardValGroup: {
    display: 'flex',
    alignItems: 'baseline',
    gap: '8px',
    marginTop: '14px',
  },
  cardNum: {
    fontSize: '34px',
    fontWeight: 800,
    letterSpacing: '-0.04em',
    color: 'var(--text-main)',
  },
  subNum: {
    fontSize: '12px',
    color: 'var(--text-muted)',
  },
  progressBg: {
    height: '8px',
    backgroundColor: 'var(--bg-muted)',
    borderRadius: '999px',
    marginTop: '16px',
    overflow: 'hidden',
  },
  progressBar: {
    height: '100%',
    borderRadius: '999px',
    transition: 'width 0.45s ease',
  },
  chartSection: {
    backgroundColor: 'var(--bg-elevated)',
    backdropFilter: 'blur(10px)',
    border: '1px solid var(--border-color)',
    borderRadius: 'var(--radius-lg)',
    padding: '22px',
    marginBottom: '22px',
    boxShadow: 'var(--shadow-soft)',
  },
  sectionTitle: {
    fontSize: '18px',
    fontWeight: 800,
    margin: 0,
    color: 'var(--text-main)',
  },
  sectionSubtitle: {
    fontSize: '13px',
    color: 'var(--text-muted)',
    margin: '6px 0 0 0',
    lineHeight: 1.6,
  },
  alertSection: {
    backgroundColor: 'var(--bg-elevated)',
    backdropFilter: 'blur(10px)',
    border: '1px solid rgba(194, 59, 59, 0.18)',
    borderRadius: 'var(--radius-lg)',
    padding: '22px',
    boxShadow: 'var(--shadow-soft)',
  },
  alertGrid: {
    display: 'grid',
    gridTemplateColumns: 'repeat(auto-fit, minmax(280px, 1fr))',
    gap: '12px',
    marginTop: '16px',
  },
  alertItem: {
    backgroundColor: 'rgba(194, 59, 59, 0.05)',
    borderRight: '4px solid var(--danger)',
    padding: '14px',
    borderRadius: 'var(--radius-md)',
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    gap: '10px',
  },
  severityTag: {
    backgroundColor: 'var(--danger)',
    color: '#fff',
    fontSize: '10px',
    fontWeight: 700,
    padding: '3px 7px',
    borderRadius: '6px',
  },
  alertAction: {
    display: 'inline-flex',
    alignItems: 'center',
    gap: '4px',
    backgroundColor: 'var(--bg-solid)',
    color: 'var(--text-main)',
    border: '1px solid var(--border-color)',
    borderRadius: '999px',
    padding: '6px 10px',
    cursor: 'pointer',
    fontFamily: 'var(--font-ui)',
    fontSize: '12px',
    fontWeight: 600,
  },
  monitorForm: {
    display: 'grid',
    gridTemplateColumns: 'repeat(auto-fit, minmax(180px, 1fr))',
    gap: '12px',
    alignItems: 'end',
    marginTop: '18px',
  },
  monitorLabel: {
    display: 'flex',
    flexDirection: 'column',
    gap: '6px',
    fontSize: '12px',
    color: 'var(--text-muted)',
    fontWeight: 600,
  },
  monitorInput: {
    backgroundColor: 'var(--bg-solid)',
    color: 'var(--text-main)',
    border: '1px solid var(--border-strong)',
    borderRadius: 'var(--radius-md)',
    padding: '11px 12px',
    fontFamily: 'inherit',
    fontSize: '14px',
  },
  monitorSubmit: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    gap: '6px',
    backgroundColor: 'var(--primary)',
    color: '#fff',
    border: 'none',
    borderRadius: '999px',
    padding: '11px 16px',
    cursor: 'pointer',
    fontFamily: 'var(--font-ui)',
    fontWeight: 700,
    fontSize: '13px',
    whiteSpace: 'nowrap',
  },
  monitorList: {
    display: 'flex',
    flexDirection: 'column',
    gap: '10px',
    marginTop: '18px',
  },
  monitorRow: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    gap: '12px',
    backgroundColor: 'var(--bg-solid)',
    border: '1px solid var(--border-color)',
    borderRadius: 'var(--radius-md)',
    padding: '14px 16px',
  },
  monitorDelete: {
    backgroundColor: 'transparent',
    color: 'var(--text-muted)',
    border: '1px solid var(--border-color)',
    borderRadius: '10px',
    padding: '8px',
    cursor: 'pointer',
    display: 'flex',
  },
};
